server:
  port: 11923
spring:
  application:
    name: chatting-software-backend
  datasource:
    url: jdbc:mysql://localhost:3306/question-and-answer-platform?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      timeout: 3000
      port: 6379


logging:
  level:
    org:
      springframework:
        web: DEBUG